# Generated by Django 3.0.5 on 2020-04-11 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeRatingXP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.CharField(max_length=10)),
                ('xp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CountryZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('predominant_climate', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country', to='elorin.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('script', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subspecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subspecies_zone', to='elorin.CountryZone')),
                ('primary_language', models.ManyToManyField(related_name='languages', to='elorin.Language')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species', to='elorin.Species')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type_of_place', models.CharField(max_length=100)),
                ('commentary', models.CharField(max_length=1000)),
                ('country_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone', to='elorin.CountryZone')),
            ],
        ),
        migrations.CreateModel(
            name='CulturalItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type_of_thing', models.CharField(max_length=100)),
                ('commentary', models.CharField(max_length=1000)),
                ('country_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultural_item_zone', to='elorin.CountryZone')),
                ('subspecies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subspecies', to='elorin.Subspecies')),
            ],
        ),
    ]
