# Generated by Django 2.2.9 on 2020-02-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elorin', '0002_challengeratingxp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengeratingxp',
            name='challenge',
            field=models.CharField(max_length=10),
        ),
    ]
